version: '2.0'
services:
  media_conduit:
    container_name: "media_repo_conduit"
    build:
      context: '.'
      dockerfile: 'Conduit.Dockerfile'
    restart: unless-stopped
    volumes:
      - ./conduit-db:/srv/conduit/.local/share/conduit
    environment:
      ROCKET_SERVER_NAME: "localhost"
      ROCKET_PORT: 8004
      ROCKET_REGISTRATION_DISABLED: "false"
      ROCKET_ENCRYPTION_DISABLED: "false"
    networks:
      - media_proxy
  media_nginx:
    container_name: "media_repo_nginx"
    image: "nginx:latest"
    restart: unless-stopped
    volumes:
      - ./conduit.nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8008:80"
    networks:
      - media_proxy
  media_element:
    container_name: "media_repo_element"
    image: "vectorim/riot-web:latest"
    restart: unless-stopped
    volumes:
      - ./element-config.json:/app/config.json
    networks:
      - media_proxy
networks:
  media_proxy:
